-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 13:20:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema innovation_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `innovation_db` ;

-- -----------------------------------------------------
-- Schema innovation_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `innovation_db` DEFAULT CHARACTER SET utf8 ;
USE `innovation_db` ;

-- -----------------------------------------------------
-- Table `innovation_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`user` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`user` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `user_sex` VARCHAR(1) NOT NULL,
  `user_mail` VARCHAR(50) NULL,
  `user_phone` VARCHAR(20) NULL,
  `account_state` VARCHAR(20) NOT NULL DEFAULT '待审核' COMMENT '账号状态： 待审核、可用、不可用',
  `user_identity` VARCHAR(10) NOT NULL COMMENT '用户类型：学生、教师、企业及其他人员等，外键至user_identity表',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`student` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`student` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `student_academy` VARCHAR(20) NOT NULL,
  `student_department` VARCHAR(20) NOT NULL,
  `student_major` VARCHAR(20) NOT NULL,
  `student_class` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`teacher` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`teacher` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `teacher_degree` VARCHAR(20) NOT NULL,
  `teacher_bachelor` VARCHAR(20) NOT NULL,
  `teacher_major` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`company` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`company` (
  `user_id` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `company_name` VARCHAR(120) NOT NULL,
  `company_phone` VARCHAR(20) NOT NULL,
  `company_principal` VARCHAR(50) NOT NULL,
  `company_address` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`user_identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`user_identity` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`user_identity` (
  `user_identity_id` VARCHAR(10) NOT NULL,
  `user_identity_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_identity_id`),
  UNIQUE INDEX `user_identity_id_UNIQUE` (`user_identity_id` ASC),
  UNIQUE INDEX `user_identity_name_UNIQUE` (`user_identity_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`dependent_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`dependent_unit` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`dependent_unit` (
  `unit_id` VARCHAR(20) NOT NULL,
  `unit_name` VARCHAR(50) NOT NULL,
  `unit_identity` VARCHAR(10) NOT NULL,
  `unit_address` VARCHAR(120) NOT NULL,
  `unit_principal` VARCHAR(20) NOT NULL,
  `unti_phone` VARCHAR(20) NOT NULL,
  `unit_state` VARCHAR(45) NULL,
  PRIMARY KEY (`unit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`dependent_unit_identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`dependent_unit_identity` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`dependent_unit_identity` (
  `identity_id` VARCHAR(20) NOT NULL,
  `identity_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`identity_id`),
  UNIQUE INDEX `identity_id_UNIQUE` (`identity_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`team` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`team` (
  `team_id` VARCHAR(20) NOT NULL,
  `team_name` VARCHAR(50) NOT NULL,
  `team_dependent_unit` VARCHAR(20) NOT NULL,
  `team_teacher` VARCHAR(20) NULL,
  `team_principal` VARCHAR(20) NOT NULL,
  `team_introduction` VARCHAR(200) NULL,
  `team_state` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`project` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`project` (
  `project_id` VARCHAR(20) NOT NULL,
  `project_name` VARCHAR(50) NOT NULL,
  `project_identity` VARCHAR(20) NOT NULL,
  `project_level` VARCHAR(20) NOT NULL,
  `team_id` VARCHAR(20) NOT NULL,
  `project_teacher` VARCHAR(20) NOT NULL,
  `project_principal` VARCHAR(20) NOT NULL,
  `register_year` DATE NOT NULL,
  `start_year` DATE NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`project_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`project_files` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`project_files` (
  `project_id` VARCHAR(20) NOT NULL,
  `file_path` VARCHAR(200) NOT NULL,
  `file_type` TINYINT NOT NULL COMMENT '文件类型：申请材料还是结题材料',
  PRIMARY KEY (`project_id`, `file_path`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`project_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`project_student` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`project_student` (
  `project_id` VARCHAR(20) NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `add_time` DATE NOT NULL,
  `leave_time` DATE NULL,
  `is_in_service` TINYINT NOT NULL DEFAULT 1 COMMENT '是否在项目中，是为 1，否为 0',
  PRIMARY KEY (`project_id`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`award_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`award_name` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`award_name` (
  `award_id` VARCHAR(20) NOT NULL,
  `award_name` VARCHAR(50) NOT NULL COMMENT '奖项名称表：服务外包大赛、创新创业大赛等名称',
  PRIMARY KEY (`award_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`award_identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`award_identity` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`award_identity` (
  `identity_id` VARCHAR(20) NOT NULL,
  `identity_name` VARCHAR(50) NOT NULL COMMENT '获奖类别表：国家级、省级、校级等 ',
  PRIMARY KEY (`identity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`award_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`award_level` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`award_level` (
  `level_id` VARCHAR(20) NOT NULL,
  `level_name` VARCHAR(50) NULL COMMENT '获奖等级表：一等奖、二等奖、三等奖、金奖等',
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`award_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`award_user` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`award_user` (
  `award_name` VARCHAR(50) NOT NULL,
  `award_identity` VARCHAR(50) NOT NULL,
  `award_level` VARCHAR(50) NOT NULL,
  `award_time` DATE NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`award_name`, `award_identity`, `award_level`, `award_time`, `user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`award_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`award_project` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`award_project` (
  `award_name` VARCHAR(50) NOT NULL,
  `award_identity` VARCHAR(50) NOT NULL,
  `award_level` VARCHAR(50) NOT NULL,
  `award_time` DATE NOT NULL,
  `dependent_unit_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`award_name`, `award_identity`, `award_level`, `award_time`, `dependent_unit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`policy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`policy` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`policy` (
  `policy_id` VARCHAR(20) NOT NULL,
  `policy_title` VARCHAR(50) NOT NULL,
  `policy_identity` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `publish_time` DATE NOT NULL,
  `publish_user` VARCHAR(50) NOT NULL,
  `policy_introduction` TEXT NULL,
  PRIMARY KEY (`policy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`policy_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`policy_files` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`policy_files` (
  `policy_id` VARCHAR(20) NOT NULL,
  `file_path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`policy_id`, `file_path`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`policy_identity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`policy_identity` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`policy_identity` (
  `identity_id` VARCHAR(20) NOT NULL,
  `identity_name` VARCHAR(50) NULL,
  PRIMARY KEY (`identity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`notification` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`notification` (
  `notification_id` VARCHAR(20) NOT NULL,
  `notification_title` VARCHAR(50) NOT NULL,
  `notification_identity` VARCHAR(50) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `publish_time` DATE NOT NULL,
  `publish_user` VARCHAR(20) NOT NULL,
  `notification_introduction` TEXT NOT NULL,
  PRIMARY KEY (`notification_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`notification_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`notification_files` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`notification_files` (
  `notification_id` VARCHAR(20) NOT NULL,
  `file_path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`notification_id`, `file_path`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`file_system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`file_system` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`file_system` (
  `file_system_id` VARCHAR(20) NOT NULL,
  `state` VARCHAR(50) NOT NULL,
  `publish_time` DATE NOT NULL,
  `effective_time` DATE NOT NULL,
  `publish_user` VARCHAR(50) NOT NULL,
  `introduction` TEXT NULL,
  PRIMARY KEY (`file_system_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`file_system_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`file_system_files` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`file_system_files` (
  `file_system_id` VARCHAR(20) NOT NULL,
  `file_path` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`file_system_id`, `file_path`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`admc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`admc` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`admc` (
  `academy` VARCHAR(20) NOT NULL,
  `department` VARCHAR(20) NOT NULL,
  `major` VARCHAR(20) NOT NULL,
  `_class` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`academy`, `department`, `major`, `_class`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `innovation_db`.`_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `innovation_db`.`_state` ;

CREATE TABLE IF NOT EXISTS `innovation_db`.`_state` (
  `state_id` VARCHAR(20) NOT NULL,
  `state_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
